- name: ensure mariadb is installed
  apt:
    name: 
      - mariadb-server
      - python3-mysqldb

- name: create database for jose
  mysql_db: 
    name: "jose"
    state: present

- name: create user mysql for jose
  mysql_user: 
    name: "jose"
    host: "{{ item }}"
    password: "jose"
    priv: "jose.*:ALL,GRANT"
  with_items:
    - localhost

- name: mariadb listen only on localhost
  lineinfile: 
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address"
    line: "bind-address = 127.0.0.1"
    state: present
  notify:
    - restart mariadb
